version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Run linting and analysis - you can comment out or remove this step
      # - run:
      #     name: Run Python Analysis
      #     command: |
      #       pip install pylint
      #       pylint your_python_code.py

      - run:
          name: Run Tests
          command: |
            pip install -r requirements.txt

workflows:
  version: 2
  build_and_test:
