name: PyLint Linter check
on:
  push:
    branches:
      - main
      - dev

jobs:
  PyLint-Check:
    runs-on: ubuntu-latest

    container: alpine

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v3

        - name: Checkout submodules
          uses: textbook/git-checkout-submodule-action@master

        - name: Copy data.
          run: |
              cp -r "$(pwd)" /source

        - name: Run Init.
          run: cd /source && sh pylint.sh
