name: PyLint Linter check
on:
  push:
    branches:
      - master
      - main

jobs:
  PyLint-Check:
    runs-on: ubuntu-latest

    container: alpine

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v3

        - name: Copy data.
          run: |
              cp -r "$(pwd)" /source

        - name: Initialize submodules.
          run: |
              cd /source
              apk add --no-cache git
              git submodule update --remote

        - name: Run Init.
          run: cd /source && sh pylint.sh
