name: PyLint Linter check
on:
  push:
    branches:
      - main
      - dev

jobs:
  PyLint-Check:
    runs-on: ubuntu-latest

    container: alpine

    steps:
        - name: Setup basic environment
          run: |
              echo "LOCAL_DIR=$(pwd)" >> $GITHUB_ENV
              echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        - name: ^ Checkout
          run: |
              apk add --no-cache git
              cd /
              git clone --recursive -b $GIT_BRANCH https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }} repo
              rm -rf "$LOCAL_DIR"
              mv repo "$LOCAL_DIR"

        - name: Copy data.
          run: |
              cp -r "$(pwd)" /source

        - name: Run Init.
          run: |
              cd /source
              sh pylint.sh 2>&1 3>&1 | tee /pylint-"$(date +%Y-%m-%d)".log

        - name: Publish the log.
          run: |
              mkdir /artifacts
              mv /pylint-* /artifacts/

        - name: Upload Log.
          uses: actions/upload-artifact@v3
          with:
            name: PyLint Log
            path: /artifacts
